# Generated by Django 5.2.6 on 2026-02-01 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('probability', models.FloatField()),
                ('threshold', models.FloatField(default=0.5)),
                ('label', models.CharField(max_length=50)),
                ('recommendations_ar', models.TextField(blank=True, default='')),
                ('recommendations_en', models.TextField(blank=True, default='')),
                ('recommendations_status_ar', models.CharField(default='pending', max_length=20)),
                ('recommendations_status_en', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
