# Generated by Django 5.2.10 on 2026-01-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='recommendations_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='recommendations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
