# Generated by Django 5.2.10 on 2026-02-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_recommendations_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='recommendations',
            new_name='recommendations_ar',
        ),
        migrations.RenameField(
            model_name='analysisresult',
            old_name='recommendations_status',
            new_name='recommendations_status_ar',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='recommendations_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='recommendations_status_en',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
