# Generated by Django 5.2.10 on 2026-01-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(choices=[('demo', 'Request a demo'), ('support', 'Support'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
