# Generated by Django 6.0.1 on 2026-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('Project_type', models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('project_location', models.CharField(max_length=50)),
                ('project_location_type', models.CharField(choices=[('On-site', 'On-site'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('project_budget', models.FloatField()),
                ('project_duration', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('economic_indicator', models.TextField(editable=False)),
                ('Number_of_Similar_Enterprises', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects_table',
            },
        ),
    ]
