# Generated by Django 6.0.1 on 2026-01-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Project_type',
            field=models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Hybrid', 'Hybrid')], db_column='Project_type', max_length=50),
        ),
    ]
