# Generated by Django 6.0.1 on 2026-01-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0004_alter_projects_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='economic_indicator',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
