# Generated by Django 5.2.10 on 2026-02-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0004_projects_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Number_of_Similar_Enterprises',
        ),
        migrations.AddField(
            model_name='projects',
            name='num_of_similar_enterprises',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
