<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-02-09 19:20
=======
# Generated by Django 5.2.10 on 2026-02-10 04:09
>>>>>>> c6a9ebd81174396c80c122f64432fee802901f5f

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0004_projects_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Number_of_Similar_Enterprises',
        ),
        migrations.AddField(
            model_name='projects',
            name='num_of_similar_enterprises',
<<<<<<< HEAD
            field=models.IntegerField(blank=True, null=True),
=======
            field=models.IntegerField(blank=True, editable=False, null=True),
>>>>>>> c6a9ebd81174396c80c122f64432fee802901f5f
        ),
    ]
