# Generated by Django 5.2.10 on 2026-02-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0005_remove_projects_number_of_similar_enterprises_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_city',
            field=models.CharField(blank=True, choices=[('', '---------'), ('riyadh', 'الرياض'), ('diriyah', 'الدرعية'), ('kharj', 'الخرج'), ('buraidah', 'بريدة'), ('unaizah', 'عنيزة'), ('ras', 'الرس'), ('dammam', 'الدمام'), ('khobar', 'الخبر'), ('dhahran', 'الظهران'), ('jubail', 'الجبيل'), ('jeddah', 'جدة'), ('taif', 'الطائف'), ('madinah', 'المدينة المنورة'), ('abha', 'أبها'), ('khamees', 'خميس مشيط'), ('tabuk', 'تبوك'), ('jazan', 'جازان'), ('hail', 'حائل'), ('sakaka', 'سكاكا'), ('arar', 'عرعر'), ('najran', 'نجران'), ('bahah', 'الباحة'), ('other', 'أخرى')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_location',
            field=models.CharField(choices=[('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_region',
            field=models.CharField(blank=True, choices=[('', '---------'), ('riyadh', 'منطقة الرياض'), ('qassim', 'منطقة القصيم'), ('eastern', 'المنطقة الشرقية'), ('makkah', 'منطقة مكة المكرمة'), ('madinah', 'منطقة المدينة المنورة'), ('asir', 'منطقة عسير'), ('tabuk', 'منطقة تبوك'), ('jazan', 'منطقة جازان'), ('hail', 'منطقة حائل'), ('jouf', 'منطقة الجوف'), ('najran', 'منطقة نجران'), ('bahah', 'منطقة الباحة'), ('northern', 'منطقة الحدود الشمالية'), ('other', 'أخرى')], max_length=30, null=True),
        ),
    ]
