# Generated by Django 6.0.1 on 2026-01-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0005_alter_projects_economic_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_budget',
            field=models.IntegerField(),
        ),
    ]
