# Generated by Django 5.2.10 on 2026-02-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0006_alter_projects_project_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='economic_indicator',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
