# Generated by Django 6.0.1 on 2026-01-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0006_alter_projects_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='economic_indicator',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
