# Generated by Django 5.2.10 on 2026-02-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0008_alter_projects_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Project_type',
            field=models.CharField(choices=[('service', 'Service'), ('product', 'Product'), ('hybrid', 'Hybrid')], db_column='Project_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_city',
            field=models.CharField(blank=True, choices=[('', '---------'), ('riyadh', 'Riyadh'), ('diriyah', 'Diriyah'), ('kharj', 'Al Kharj'), ('buraidah', 'Buraidah'), ('unaizah', 'Unaizah'), ('ras', 'Ar Rass'), ('dammam', 'Dammam'), ('khobar', 'Khobar'), ('dhahran', 'Dhahran'), ('jubail', 'Jubail'), ('jeddah', 'Jeddah'), ('taif', 'Taif'), ('madinah', 'Madinah'), ('abha', 'Abha'), ('khamees', 'Khamis Mushait'), ('tabuk', 'Tabuk'), ('jazan', 'Jazan'), ('hail', 'Hail'), ('sakaka', 'Sakaka'), ('arar', 'Arar'), ('najran', 'Najran'), ('bahah', 'Al Bahah'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_location',
            field=models.CharField(choices=[('other', 'Other')], default='other', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_location_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('online', 'Online'), ('hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_region',
            field=models.CharField(blank=True, choices=[('', '---------'), ('riyadh', 'Riyadh Region'), ('qassim', 'Qassim Region'), ('eastern', 'Eastern Region'), ('makkah', 'Makkah Region'), ('madinah', 'Madinah Region'), ('asir', 'Asir Region'), ('tabuk', 'Tabuk Region'), ('jazan', 'Jazan Region'), ('hail', 'Hail Region'), ('jouf', 'Al Jouf Region'), ('najran', 'Najran Region'), ('bahah', 'Al Bahah Region'), ('northern', 'Northern Borders'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
