# Generated by Django 5.2.10 on 2026-02-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0009_alter_projects_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Project_type',
            field=models.CharField(choices=[('Service', 'Service'), ('Product', 'Product'), ('Hybrid', 'Hybrid')], db_column='Project_type', max_length=50),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_location',
            field=models.CharField(choices=[('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_location_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Online', 'Online'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
