# Generated by Django 6.0.1 on 2026-02-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0010_alter_projects_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='num_of_similar_enterprises',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
