# Generated by Django 6.0.1 on 2026-01-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0011_alter_projects_economic_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
    ]
