# Generated by Django 5.2.10 on 2026-02-15 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0011_alter_projects_num_of_similar_enterprises'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwa_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
