# Generated by Django 6.0.1 on 2026-01-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0012_remove_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='economic_indicator',
            field=models.CharField(blank=True, editable=False, null=True),
        ),
    ]
