# Generated by Django 5.2.10 on 2026-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0014_user_bio_user_city_user_linkedin_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city_custom',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region_custom',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
