# Generated by Django 6.0.2 on 2026-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0016_user_activation_token_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField()),
                ('key', models.CharField()),
                ('content', models.TextField()),
            ],
        ),
    ]
