# Generated by Django 6.0.2 on 2026-02-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0017_sitecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='page',
        ),
    ]
