# Generated by Django 6.0.2 on 2026-02-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0019_contactmessage_is_replied_contactmessage_reply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
    ]
