# Generated by Django 6.0.2 on 2026-03-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0020_remove_contactmessage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='is_replied',
            new_name='is_read',
        ),
    ]
