# Generated by Django 6.0.2 on 2026-03-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0021_rename_is_replied_contactmessage_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='is_read',
            new_name='is_replied',
        ),
    ]
