# Generated by Django 5.2.10 on 2026-03-05 21:07

from django.db import migrations


def add_reply_column(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return

    table = "JADWA_AI_contactmessage"
    col = "reply"

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"PRAGMA table_info({table});")
        cols = [row[1] for row in cursor.fetchall()]
        if col not in cols:
            cursor.execute(f"ALTER TABLE {table} ADD COLUMN {col} TEXT;")


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0022_rename_is_read_contactmessage_is_replied'),
    ]

    operations = [
        migrations.RunPython(add_reply_column, reverse_code=migrations.RunPython.noop),
    ]