# Generated by Django 5.2.10 on 2026-03-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0023_fix_contactmessage_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='sitecontent',
            name='key',
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='about_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_city',
            field=models.CharField(blank=True, choices=[('', 'Select city'), ('riyadh', 'Riyadh'), ('diriyah', 'Diriyah'), ('kharj', 'Al Kharj'), ('buraidah', 'Buraidah'), ('unaizah', 'Unaizah'), ('ras', 'Ar Rass'), ('dammam', 'Dammam'), ('khobar', 'Khobar'), ('dhahran', 'Dhahran'), ('jubail', 'Jubail'), ('jeddah', 'Jeddah'), ('taif', 'Taif'), ('madinah', 'Madinah'), ('abha', 'Abha'), ('khamees', 'Khamis Mushait'), ('tabuk', 'Tabuk'), ('jazan', 'Jazan'), ('hail', 'Hail'), ('sakaka', 'Sakaka'), ('arar', 'Arar'), ('najran', 'Najran'), ('bahah', 'Al Bahah'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_region',
            field=models.CharField(blank=True, choices=[('', 'Select region'), ('riyadh', 'Riyadh Region'), ('qassim', 'Qassim Region'), ('eastern', 'Eastern Region'), ('makkah', 'Makkah Region'), ('madinah', 'Madinah Region'), ('asir', 'Asir Region'), ('tabuk', 'Tabuk Region'), ('jazan', 'Jazan Region'), ('hail', 'Hail Region'), ('jouf', 'Al Jouf Region'), ('najran', 'Najran Region'), ('bahah', 'Al Bahah Region'), ('northern', 'Northern Borders'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
