# Generated by Django 5.2.10 on 2026-03-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JADWA_AI', '0024_remove_sitecontent_content_remove_sitecontent_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecontent',
            old_name='about_text',
            new_name='how_desc',
        ),
        migrations.RenameField(
            model_name='sitecontent',
            old_name='about_title',
            new_name='how_title',
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='product_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='product_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stories_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='stories_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
